version: '3.8'

services:
 app_backend:
  build: ./app
  container_name: app_backend
  command: uvicorn main:app --host 0.0.0.0 --port 8000
  ports:
    - "8000:8000"
  restart: always
 app_frontend:
  build: ./frontend
  container_name: app_frontend
  command: npm run serve
  ports:
    - "8080:8080"
  depends_on:
    - "app_backend"
  restart: always